version: '3.8'

services:

  # User Service
  user-service:
    build:
      context: user-management
    container_name: user_management
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/user_management_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - app-network

  # Task Service
  task-service:
    build:
      context: task-management
    container_name: task_management
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/task_management_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - app-network

  # Project Service
  project-service:
    build:
      context: project-management
    container_name: project_management
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/project_management_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - app-network

  # Notification Service
  notification-service:
    build:
      context: notification-management
    container_name: notification_management
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/notification_management_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - app-network

  # Team Service
  team-service:
    build:
      context: team-management
    container_name: team_management
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/team_management_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - app-network


# Define a network for internal communication
networks:
  app-network:
    driver: bridge

# Define persistent volume for MySQL
volumes:
  mysql_data:
