services:

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_management_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  graphql-gateway:
    build:
      context: graphql-gateway
    container_name: graphql_gateway
    ports:
      - "8083:8083"
    networks:
      - app-network

  app:
    build: .
    container_name: project-management
    ports:
      - "8083:8083"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/project_management_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

volumes:
  mysql_data: