spring:
  application:
    name: notification-management

  datasource:
    url: jdbc:mysql://localhost:3306/notification_management?createDatabaseIfNotExist=true
    username: root
    password: Hasitha@8465

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-management
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'


    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      template:
        default-topic: notification-events

  mail:
    host: smtp.gmail.com
    port: 587
    username: "hasithamadushanepa076@gmail.com"
    password: "agsg eebs jvay dapa"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8084
